data<-read.csv(file.choose(),header=TRUE)
summary(data)
str(data)
head(data)
dim(data)
library(Amelia)
missmap(data)
sum(is.na(data$male))
sum(is.na(data$age))
sum(is.na(data$currentSmoker))
mean(data[,3],na.rm=TRUE)
sum(is.na(data$prevalentStroke))

sum(is.na(data$prevalentHyp))
median(data[,5],na.rm=TRUE)
sum(is.na(data$diabetes))
median(data[,6],na.rm=TRUE)
sum(is.na(data$sysBP))
sum(is.na(data$diaBP))
sum(is.na(data))
median(data[,7])
median(data[,8])
median(data[,9])
median(data[,10],na.rm=TRUE)
median(data[,11])
median(data[,12])
median(data[,13],na.rm=TRUE)
median(data[,14],na.rm=TRUE)
median(data[,15],na.rm=TRUE)
sum(is.na(data[,15]))
for(i in 1:ncol(data)){
  data[is.na(data[,i]), i] <- median(data[,i], na.rm = TRUE)
}
missmap(data)
getwd()
write.csv(data,file="framinghammedian.csv")
