data<-read.csv(file.choose(),header=TRUE)
str(data)
head(data)
dim(data)
library(Amelia)
missmap(data)
sum(is.na(data$male))
sum(is.na(data$age))
sum(is.na(data$currentSmoker))
mean(data[,3],na.rm=TRUE)
sum(is.na(data$prevalentStroke))

sum(is.na(data$prevalentHyp))
mean(data[,5],na.rm=TRUE)
sum(is.na(data$diabetes))
mean(data[,6],na.rm=TRUE)
sum(is.na(data$sysBP))
sum(is.na(data$diaBP))
sum(is.na(data))
mean(data[,7])
mean(data[,8])
mean(data[,9])
mean(data[,10],na.rm=TRUE)
mean(data[,11])
mean(data[,12])
mean(data[,13],na.rm=TRUE)
mean(data[,14],na.rm=TRUE)
mean(data[,15],na.rm=TRUE)
sum(is.na(data[,15]))
for(i in 1:ncol(data)){
  data[is.na(data[,i]), i] <- mean(data[,i], na.rm = TRUE)
}
missmap(data)
write.csv(data,"framingham1.csv")
